# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_data',
            name='cat_1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
