# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_db', '0002_auto_20170429_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_data',
            name='cat_1',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='document_data',
            name='cat_2',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='document_data',
            name='cat_3',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='document_data',
            name='cat_4',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='document_data',
            name='cat_5',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='document_data',
            name='cat_6',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='document_data',
            name='cat_7',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='document_data',
            name='cat_8',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='document_data',
            name='cat_9',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
