# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0003_auto_20170604_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meal Type',
                'verbose_name_plural': 'Meal Types',
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
