# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0005_dishes_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='meal_type',
            field=models.ManyToManyField(blank=True, null=True, to='dinner.meal'),
        ),
    ]
