# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0006_auto_20170604_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='meal_type',
            field=models.ManyToManyField(to='dinner.meal'),
        ),
    ]
