# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-18 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='redirect_elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('redirect_url', models.URLField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Redirect Element',
                'verbose_name_plural': 'Redirect Elements',
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
