# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 21:35
from __future__ import unicode_literals

import blogs.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('detail', models.TextField(max_length=2300)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=blogs.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('draft', models.BooleanField(default=False)),
                ('publish', models.DateField(default=datetime.datetime(2017, 5, 11, 21, 35, 58, 84491, tzinfo=utc))),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
