# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 14:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20170512_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taggers',
            options={'ordering': ['-tag_name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 5, 14, 14, 19, 25, 715578, tzinfo=utc)),
        ),
    ]
