# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 10:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20170514_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 5, 16, 10, 16, 30, 629693, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blogs.taggers'),
        ),
    ]
