# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 03:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_auto_20170604_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 6, 4, 3, 45, 48, 558795, tzinfo=utc)),
        ),
    ]
