# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_auto_20170613_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 6, 13, 15, 50, 28, 301922, tzinfo=utc)),
        ),
    ]
