# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 10:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0023_auto_20170614_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 6, 14, 10, 30, 56, 969118, tzinfo=utc)),
        ),
    ]
