# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 16:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0024_auto_20170614_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 6, 15, 16, 2, 57, 347018, tzinfo=utc)),
        ),
    ]
