# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 16:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0025_auto_20170615_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 6, 15, 16, 5, 6, 940501, tzinfo=utc)),
        ),
    ]
