# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-23 15:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0027_auto_20170714_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 7, 23, 15, 30, 53, 591797, tzinfo=utc)),
        ),
    ]
