# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-18 09:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0048_auto_20180223_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2018, 4, 18, 9, 6, 36, 310454, tzinfo=utc)),
        ),
    ]
