# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-18 09:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0049_auto_20180418_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2018, 4, 18, 9, 23, 22, 238981, tzinfo=utc)),
        ),
    ]
