# Generated by Django 2.2.1 on 2019-06-17 06:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0052_auto_20190510_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2019, 6, 17, 6, 10, 16, 690373, tzinfo=utc)),
        ),
    ]
