# Generated by Django 2.2.1 on 2019-06-17 06:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0053_auto_20190617_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2019, 6, 17, 6, 32, 27, 407531, tzinfo=utc)),
        ),
    ]
