# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-02 05:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tweetme.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tweeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.TextField(max_length='twitter_length')),
                ('tweeton', models.DateTimeField(default=datetime.datetime(2017, 12, 2, 5, 35, 58, 936912, tzinfo=utc))),
                ('image_upload', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=tweetme.models.upload_location, width_field='width_field')),
                ('image_url', models.TextField(blank=True, max_length=1400, null=True)),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('twitter_length', models.IntegerField(choices=[(140, '140'), (280, '280')])),
                ('status', models.IntegerField(choices=[(0, 'Scheduled'), (1, 'Tweeted'), (2, 'Error')])),
                ('image_type', models.IntegerField(choices=[(0, 'Nill'), (1, 'Attached'), (2, 'URL')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp', '-updated', '-tweeton'],
            },
        ),
    ]
