# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-02 05:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweetme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweeting',
            name='twitter_length',
        ),
        migrations.AlterField(
            model_name='tweeting',
            name='tweet',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='tweeting',
            name='tweeton',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 2, 5, 44, 13, 237928, tzinfo=utc)),
        ),
    ]
