# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-02 06:00
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweetme', '0002_auto_20171202_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweeting',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tweeting',
            name='tweeton',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 2, 6, 0, 14, 713344, tzinfo=utc)),
        ),
    ]
