# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-02 08:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweetme', '0003_auto_20171202_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweeting',
            name='image_type',
            field=models.IntegerField(choices=[(0, 'Nill'), (1, 'Attached'), (2, 'URL')], default=0),
        ),
        migrations.AlterField(
            model_name='tweeting',
            name='status',
            field=models.IntegerField(choices=[(0, 'Scheduled'), (1, 'Tweeted'), (2, 'Error')], default=0),
        ),
        migrations.AlterField(
            model_name='tweeting',
            name='tweeton',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 2, 8, 49, 23, 288641, tzinfo=utc)),
        ),
    ]
