# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-22 20:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweetme', '0004_auto_20171202_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweeting',
            name='tweeton',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 20, 23, 2, 170423, tzinfo=utc)),
        ),
    ]
