# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-18 09:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweetme', '0006_auto_20180418_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweeting',
            name='tweeton',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 18, 9, 23, 22, 251378, tzinfo=utc)),
        ),
    ]
