# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='document_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_0', models.IntegerField(choices=[(1, 'Industrial Exposure & Experience'), (2, 'Alma Mater'), (3, 'Achievement'), (4, 'Area of Interest'), (5, 'Educational Activities'), (6, 'Work In Process'), (7, 'Activities at the moment'), (8, 'Personality, Qualities & Skills'), (9, 'Guest Lectures'), (10, 'Books Author'), (11, 'Special Recognised'), (12, 'Competitions'), (13, 'field 13'), (14, 'field 14')])),
                ('cat_1', models.TextField(blank=True, default='', null=True)),
                ('cat_2', models.TextField(blank=True, default='', null=True)),
                ('cat_3', models.TextField(blank=True, default='', null=True)),
                ('cat_4', models.TextField(blank=True, default='', null=True)),
                ('cat_5', models.TextField(blank=True, default='', null=True)),
                ('cat_6', models.TextField(blank=True, default='', null=True)),
                ('cat_7', models.TextField(blank=True, default='', null=True)),
                ('cat_8', models.TextField(blank=True, default='', null=True)),
                ('cat_9', models.TextField(blank=True, default='', null=True)),
                ('time_of_record', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-time_of_record', '-timestamp', '-updated'],
            },
        ),
    ]
