# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-23 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=1200)),
                ('hall_location', models.TextField(blank=True, max_length=12000, null=True)),
            ],
            options={
                'verbose_name': 'Function Hall',
                'verbose_name_plural': 'Function Halls',
            },
        ),
        migrations.CreateModel(
            name='bride_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1200)),
                ('father_name', models.CharField(blank=True, max_length=1200, null=True)),
            ],
            options={
                'verbose_name': 'Bride',
                'verbose_name_plural': 'Brides',
            },
        ),
        migrations.CreateModel(
            name='bridegroom_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1200)),
                ('father_name', models.CharField(blank=True, max_length=1200, null=True)),
            ],
            options={
                'verbose_name': 'Bridegroom',
                'verbose_name_plural': 'Bridegrooms',
            },
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField()),
                ('event_type', models.IntegerField(choices=[(1, 'Mahendi'), (2, 'Wedding'), (3, 'Reception')])),
                ('bride_side', models.ManyToManyField(to='cereminder.bride_list')),
                ('bridegroom_side', models.ManyToManyField(to='cereminder.bridegroom_list')),
                ('event_location', models.ManyToManyField(to='cereminder.all_location')),
                ('event_similar', models.ManyToManyField(blank=True, null=True, related_name='_events_event_similar_+', to='cereminder.events')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
