# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_auto_20170327_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywork',
            name='type_work',
            field=models.IntegerField(choices=[(1, 'Website'), (2, 'Android'), (3, 'iOS'), (4, 'Python')]),
        ),
    ]
