# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import first.models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_auto_20170604_0326'),
    ]

    operations = [
        migrations.CreateModel(
            name='hosted_projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=first.models.upload_location_hosted, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('type_work', models.IntegerField(choices=[(1, 'Website'), (2, 'Android'), (3, 'iOS'), (4, 'Python')])),
                ('role', models.IntegerField(choices=[(1, 'Design'), (2, 'Backend'), (3, 'Frontend'), (4, 'Design & Backend'), (5, 'Design & Frontend'), (6, 'Backend & Frontend'), (10, 'Design, Backend & Frontend')])),
                ('purpose', models.IntegerField(choices=[(1, 'Personal'), (2, 'Commercial'), (3, 'Contract')])),
                ('project_stage', models.IntegerField(choices=[(1, 'Idea'), (2, 'Development'), (3, 'Debugging'), (4, 'Test Users'), (5, 'Alpha'), (6, 'Beta'), (7, 'Production'), (8, 'User Acusition'), (9, 'Revenue Source'), (10, 'Breakpoint')])),
                ('detail', models.TextField(blank=True, default='', null=True)),
                ('youtube', models.TextField(blank=True, default='', null=True)),
                ('item_url', models.TextField(blank=True, default='', null=True)),
                ('created', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
