# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import first.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mywork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=first.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('type_work', models.TextField(choices=[('Website', 'Website'), ('Android', 'Android'), ('iOS', 'iOS')])),
                ('role', models.TextField(choices=[('Design', 'Design'), ('Backend', 'Backend'), ('Frontend', 'Frontend')])),
                ('purpose', models.TextField(choices=[('Personal', 'Personal'), ('Commercial', 'Commercial'), ('Contract', 'Contract')])),
                ('detail', models.TextField(blank=True, default='', null=True)),
                ('youtube', models.TextField(blank=True, default='', null=True)),
                ('item_url', models.TextField(blank=True, default='', null=True)),
                ('created', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
