# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywork',
            name='type_work',
            field=models.IntegerField(choices=[(1, 'Website'), (2, 'Android'), (3, 'iOS')]),
        ),
    ]
