# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20170327_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywork',
            name='purpose',
            field=models.IntegerField(choices=[(1, 'Personal'), (2, 'Commercial'), (3, 'Contract')]),
        ),
        migrations.AlterField(
            model_name='mywork',
            name='role',
            field=models.IntegerField(choices=[(1, 'Design'), (2, 'Backend'), (3, 'Frontend')]),
        ),
    ]
