# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_auto_20170327_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywork',
            name='role',
            field=models.IntegerField(choices=[(1, 'Design'), (2, 'Backend'), (3, 'Frontend'), (4, 'Design & Backend'), (5, 'Design & Frontend'), (6, 'Backend & Frontend'), (10, 'All')]),
        ),
    ]
