# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-30 06:03
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_hosted_projects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hosted_projects',
            options={'ordering': ['-timestamp', '-updated'], 'verbose_name': 'Hosted Website', 'verbose_name_plural': 'Hosted Websites'},
        ),
        migrations.AlterModelOptions(
            name='mywork',
            options={'ordering': ['-timestamp', '-updated'], 'verbose_name': 'Work Portfolio', 'verbose_name_plural': 'Work Portfolio'},
        ),
        migrations.AlterModelManagers(
            name='hosted_projects',
            managers=[
                ('objects_hosted', django.db.models.manager.Manager()),
            ],
        ),
    ]
