# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 03:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20170604_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 6, 4, 3, 30, 21, 397935, tzinfo=utc)),
        ),
    ]
