# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 15:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_auto_20170604_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 6, 13, 15, 49, 46, 467936, tzinfo=utc)),
        ),
    ]
