# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-23 20:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0028_auto_20170723_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 7, 23, 20, 41, 33, 484117, tzinfo=utc)),
        ),
    ]
