# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-29 07:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0045_auto_20170731_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 8, 29, 7, 59, 52, 410141, tzinfo=utc)),
        ),
    ]
