# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-02 08:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0046_auto_20170829_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 12, 2, 8, 49, 23, 273857, tzinfo=utc)),
        ),
    ]
